name: ci-secure-checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: verify path & files 
      run: |
        Pwd
        ls 
    - name: Install dependencies (if requirements.txt exists)
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt file found. Skipping dependency installation."
        fi

    - name: Run Unit Tests with Pytest
      run: |
        if [ -f tests/test_sample.py ]; then
          pytest
        else
          echo "No tests found to run with pytest."
        fi

    - name: Bandit - Python Security Linter
      run: |
        pip install bandit
        bandit -r . || { echo "Bandit scan failed with issues"; exit 1; }
