name: Secure CI Pipeline

on:
  push:
    branches:
      - CI-CD-Pipeline

permissions:
  security-events: write  # Required to upload SARIF files to GitHub

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Bandit and Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install bandit semgrep

    - name: Run Bandit (Python security scan)
      run: |
        bandit -r . -f sarif -o bandit-results.sarif

    - name: Run Semgrep (code scan)
      run: |
        semgrep --config=p/ci --sarif --output=semgrep-results.sarif

    - name: Upload Bandit SARIF results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: bandit-results.sarif

    - name: Upload Semgrep SARIF results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep-results.sarif
