name: CI Pipeline with Security Checks

on:
  push:
    branches: [ CI/CD-pipeline ]
  pull_request:
    branches: [ CI/CD-pipeline ]

jobs:
  ci-secure-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests with Pytest
        run: |
          pip install pytest
          pytest || true

      - name: Bandit - Python Security Linter
        run: |
          pip install bandit
          bandit -r . -ll --skip B101

      - name: Semgrep - Bug & Security Pattern Finder
        run: |
          curl -sL https://semgrep.dev/install.sh | sh
          ./semgrep/semgrep --config=auto --error
